'use client'

import { useEffect, useRef, useState } from 'react'
import { AssistantChatPrompt } from '@/components/app/assistant/AssistantChatPrompt'
import { AssistantChatResponse } from '@/components/app/assistant/AssistantChatResponse'
import { ScrollArea } from '@/components/ui/scroll-area'

const tokens = [
  'JavaScript',
  ' (JS)',
  ' is',
  ' one',
  ' of',
  ' the',
  ' most',
  ' popular',
  ' programming',
  ' languages,',
  ' and',
  ' widely',
  ' used',
  ' for',
  ' web',
  ' apps,',
  ' mobile',
  ' apps,',
  ' desktop',
  ' clients,',
  ' and',
  ' even',
  ' backend',
  ' development.',
  ' Due',
  ' to',
  ' its',
  ' dynamic',
  ' and',
  ' flexible',
  ' nature,',
  ' however,',
  ' JS',
  ' applications',
  ' often',
  ' have',
  ' a',
  ' reputation',
  ' for',
  ' poor',
  ' software',
  ' quality.',
  '\n',
  ' While',
  ' the',
  ' type-safe',
  ' superset',
  ' TypeScript',
  ' (TS)',
  ' offers',
  ' features',
  ' to',
  ' address',
  ' these',
  ' prejudices,',
  ' there',
  ' is',
  ' currently',
  ' insufficient',
  ' empirical',
  ' evidence',
  ' to',
  ' broadly',
  ' support',
  ' the',
  ' claim',
  ' that',
  ' TS',
  ' applications',
  ' exhibit',
  ' better',
  ' software',
  ' quality',
  ' than',
  ' JS',
  ' applications.',
  '\n',
  'We',
  ' therefore',
  ' conducted',
  ' a',
  ' repository',
  ' mining',
  ' study',
  ' based',
  ' on',
  ' 604',
  ' GitHub',
  ' projects',
  ' (299',
  ' for',
  ' JS,',
  ' 305',
  ' for',
  ' TS)',
  ' with',
  ' over',
  ' 16M',
  ' LoC.',
  ' Using',
  ' SonarQube',
  ' and',
  ' the',
  ' GitHub',
  ' API,',
  ' we',
  ' collected',
  ' and',
  ' analyzed',
  ' four',
  ' facets',
  ' of',
  ' software',
  ' quality:',
  ' a)',
  ' code',
  ' quality',
  ' (#',
  ' of',
  ' code',
  ' smells',
  ' per',
  ' LoC),',
  ' b)',
  ' code',
  ' understandability',
  ' (cognitive',
  ' complexity',
  ' per',
  ' LoC),',
  ' c)',
  ' bug',
  ' proneness',
  ' (bug',
  ' fix',
  ' commit',
  ' ratio),',
  ' and',
  ' d)',
  ' bug',
  ' resolution',
  ' time',
  ' (mean',
  ' time',
  ' a',
  ' bug',
  ' issue',
  ' is',
  ' open).',
  ' For',
  ' TS,',
  ' we',
  ' also',
  ' collected',
  ' how',
  ' frequently',
  ' the',
  ' type-safety',
  ' ignoring',
  ' any',
  ' type',
  ' was',
  ' used',
  ' per',
  ' project',
  ' via',
  ' ESLint.',
  '\n',
  'The',
  ' analysis',
  ' indicates',
  ' that',
  ' TS',
  ' applications',
  ' exhibit',
  ' significantly',
  ' better',
  ' code',
  ' quality',
  ' and',
  ' understandability',
  ' than',
  ' JS',
  ' applications.',
  ' Contrary',
  ' to',
  ' expectations,',
  ' however,',
  ' bug',
  ' proneness',
  ' and',
  ' bug',
  ' resolution',
  ' time',
  ' of',
  ' our',
  ' TS',
  ' sample',
  ' were',
  ' not',
  ' significantly',
  ' lower',
  ' than',
  ' for',
  ' JS:',
  ' the',
  ' mean',
  ' bug',
  ' fix',
  ' commit',
  ' ratio',
  ' of',
  ' TS',
  ' projects',
  ' was',
  ' more',
  ' than',
  ' 60%',
  ' larger',
  ' (0.126',
  ' vs.',
  ' 0.206),',
  ' and',
  ' TS',
  ' projects',
  ' needed',
  ' on',
  ' average',
  ' more',
  ' than',
  ' an',
  ' additional',
  ' day',
  ' to',
  ' fix',
  ' bugs',
  ' (31.86',
  ' vs.',
  ' 33.04',
  ' days).',
  ' Furthermore,',
  ' reducing',
  ' the',
  ' usage',
  ' of',
  ' the',
  ' any',
  ' type',
  ' in',
  ' TS',
  ' apps',
  ' appears',
  ' to',
  ' be',
  ' beneficial:',
  ' its',
  ' frequency',
  ' was',
  ' significantly',
  ' correlated',
  ' with',
  ' all',
  ' metrics',
  ' except',
  ' bug',
  ' proneness,',
  ' even',
  ' though',
  ' the',
  ' correlations',
  ' were',
  ' of',
  ' small',
  ' strengths',
  ' (Spearman’s',
  ' rho',
  ' between',
  ' 0.17',
  ' and',
  ' 0.26).',
]

export function AssistantChat() {
  const streamIntervalRef = useRef<ReturnType<typeof setInterval> | null>(null)

  const [content, setContent] = useState('')
  const [isStreaming, setIsStreaming] = useState(false)

  useEffect(() => {
    return () => {
      if (streamIntervalRef.current) {
        clearInterval(streamIntervalRef.current)
        streamIntervalRef.current = null
      }
    }
  }, [])

  function handleStartStreaming() {
    setIsStreaming(true)

    if (streamIntervalRef.current) {
      clearInterval(streamIntervalRef.current)
      streamIntervalRef.current = null
    }

    let currentContent = ''
    let index = 0

    setContent('')

    streamIntervalRef.current = setInterval(() => {
      if (index < tokens.length) {
        currentContent += tokens[index]
        setContent(currentContent)
        index += 1
      } else if (streamIntervalRef.current) {
        clearInterval(streamIntervalRef.current)
        streamIntervalRef.current = null
        setIsStreaming(false)
      }
    }, 50)
  }

  return (
    <div className="grid grid-rows-[1fr_auto] gap-2">
      <ScrollArea className="min-h-0">
        <AssistantChatResponse content={content} />
      </ScrollArea>

      <AssistantChatPrompt isStreaming={isStreaming} handleStartStreaming={handleStartStreaming} />
    </div>
  )
}
